name: secure_storage_helper
description: A wrapper on top of flutter_secure_storage package to use easily
repository: https://github.com/dungngminh/dungngminh-workspace

version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: 0.3.0
  very_good_analysis: 3.0.0
