name: http_client_handler
description: A wrapper on top of `http` package with GET, POST, PUT, DELELE, POST File, easier for using.
repository: https://github.com/dungngminh/dungngminh-workspace
version: 0.1.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
